from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium import webdriver
import os
import time
import config
from importlib.resources import path
import pyautogui, sys


def loginfunction(un, up):
    
    time.sleep(5)
    usernametb = config.driver.find_element_by_xpath('//*[@id="loginemail"]').send_keys(un)
    time.sleep(5)
    passwordtb = config.driver.find_element_by_xpath('//*[@id="loginpassword"]').send_keys(up)
    time.sleep(3)
    loginbtn = config.driver.find_element_by_xpath('//*[@id="mhLP-ln"]/div[2]/form/div[6]/button')
    loginbtn.click() 
    time.sleep(5)
    
def clicktabsfunction():
    
    time.sleep(3)
    PatientMngr = config.driver.find_element_by_xpath('//*[@id="sidebar"]/side-bar/div/div[1]/ul/li[3]')
    PatientMngr.click()
    time.sleep(5)
    patient = config.driver.find_element_by_xpath('//*[@id="sidebar"]/side-bar/div/div[1]/ul/li[3]/ul/li[1]/a')
    patient.click()
    time.sleep(5)
    #pageFind = config.driver.find_element_by_xpath('//*[@id="data-table-command-footer"]/div/div[1]/ul/li[4]')
    #pageFind.click()
    #time.sleep(5)
    patientName = config.driver.find_element_by_xpath('//*[@id="content"]/data/div/div[2]/div/table/tbody/tr[11]')
    patientName.click()
    time.sleep(5)
    
def editOasisfunction(comm):
    
    openOasis = config.driver.find_element_by_xpath('//*[@id="parent"]/div/div[1]/div/div[5]/div[1]/table/tbody/tr[2]/td[2]/a')
    openOasis.click()
    time.sleep(5)
    Xbtn = config.driver.find_element_by_xpath('//*[@id="closecomments"]')
    Xbtn.click()
    time.sleep(5)
    X2btn = config.driver.find_element_by_xpath('/html/body/div[11]/button')
    X2btn.click()
    time.sleep(5)
    EditOasisbtn = config.driver.find_element_by_xpath('//*[@id="titleNoteBar"]/div[4]/div[2]/button')
    EditOasisbtn.click()
    time.sleep(5)
    chooseSection = config.driver.find_element_by_xpath('//*[@id="integumentary"]/div')
    chooseSection.click()
    time.sleep(5)
    checkboxWound = config.driver.find_element_by_xpath('//*[@id="integForm"]/fieldset/div[1]/table[1]/tbody/tr[6]/td/table/tbody/tr/td[4]/div/label/input')
    checkboxWound.click()
    time.sleep(5)
    addLabelwound = config.driver.find_element_by_xpath('//*[@id="integForm"]/fieldset/div[1]/table[1]/tbody/tr[6]/td/table/tbody/tr/td[4]/div/a')
    addLabelwound.click()
    time.sleep(5)
    Woundmenu = config.driver.find_element_by_xpath('//*[@id="integForm"]/fieldset/div[1]/table[1]/tbody/tr[7]/td/table/tbody/tr/td[3]/div/div[1]/input')
    Woundmenu.click()
    time.sleep(5)
    selectWoundType = config.driver.find_element_by_xpath('//*[@id="integForm"]/fieldset/div[1]/table[1]/tbody/tr[7]/td/table/tbody/tr/td[3]/div/div[2]/ul/li[9]')
    selectWoundType.click()
    time.sleep(5)
    location = config.driver.find_element_by_xpath('//*[@id="integForm"]/fieldset/div[1]/table[1]/tbody/tr[7]/td/table/tbody/tr/td[5]/div/div[1]/input')
    location.click()
    time.sleep(5)
    selectLocation = config.driver.find_element_by_xpath('//*[@id="integForm"]/fieldset/div[1]/table[1]/tbody/tr[7]/td/table/tbody/tr/td[5]/div/div[2]/ul/li[3]')
    selectLocation.click()
    time.sleep(5)
    commenttb = config.driver.find_element_by_xpath('//*[@id="integForm"]/fieldset/div[1]/table[1]/tbody/tr[7]/td/table/tbody/tr/td[7]/input').send_keys(comm)
    time.sleep(5)
    X2btn = config.driver.find_element_by_xpath('/html/body/div[11]/button')
    X2btn.click()
    time.sleep(5)
    savebtn = config.driver.find_element_by_xpath('//*[@id="titleNoteBar"]/div[4]/div[2]/button[3]')
    savebtn.click()
    time.sleep(5)
    assessbtn = config.driver.find_element_by_xpath('/html/body/div[5]/div[2]/button[1]')
    assessbtn.click()
    time.sleep(5)

def woundcareFunction():
    
    degree = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[6]/span/table-inputs/div/div[1]/input')
    degree.click()
    time.sleep(5)
    selectDegree = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[6]/span/table-inputs/div/div[2]/ul/li[2]')
    selectDegree.click()
    time.sleep(5)
    amount = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[7]/span/table-inputs/div/div[1]/input')
    amount.click()
    time.sleep(5)
    selectAmount = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[7]/span/table-inputs/div/div[2]/ul/li[6]')
    selectAmount.click()
    time.sleep(5)
    Type = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[8]/span/table-inputs/div/div[1]/input')
    Type.click()
    time.sleep(5)
    selectType = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[8]/span/table-inputs/div/div[2]/ul/li[6]')
    selectType.click()
    time.sleep(5)
    Status = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[9]/span/table-inputs/div/div[1]/input')
    Status.click()
    time.sleep(5)
    selectStatus = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[9]/span/table-inputs/div/div[2]/ul/li[6]')
    selectStatus.click()
    time.sleep(5)
    RelatedPain = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[10]/span/table-inputs/div/div[1]/input')
    RelatedPain.click()
    time.sleep(5)
    selectScore = config.driver.find_element_by_xpath('//*[@id="goTabSection"]/div/woundcare-table/div[2]/div[2]/div/div/table-column/ul/li[10]/span/table-inputs/div/div[2]/ul/li[7]')
    selectScore.click()
    time.sleep(5)
    
    
def UploadFunction():
    upload = config.driver.find_element(By.XPATH, '//*[@id="myImg"]').click()
    time.sleep(5)
    
def mouseHover():
    
    screenWidth, screenHeight = pyautogui.size()
    time.sleep(5)
    pyautogui.click(102, 166)
    time.sleep(5)
    pyautogui.doubleClick(459, 276)
    time.sleep(5)
    pyautogui.click(241, 292)
    time.sleep(5)
    pyautogui.click(662, 573)
    time.sleep(5)

def pressDigitalMeasurement():
    
    digitalclck = config.driver.find_element_by_xpath('//*[@id="onProcessFalse-0-0"]/div[3]/div[2]/div[2]/span/div/div/a')
    digitalclck.click()
    time.sleep(20)
    EditDigitalclck = config.driver.find_element_by_xpath('//*[@id="onProcessFalse-0-0"]/div[3]/div[2]/div[2]/span/div/div/a')
    EditDigitalclck.click()
    time.sleep(5)
    pyautogui.click(1343, 718)
    pyautogui.click(1343, 718)
    pyautogui.click(1343, 718)
    pyautogui.click(1343, 718)
    pyautogui.click(1343, 718)
    time.sleep(5)
    
def WoundMeasurement():
    
    time.sleep(5)
    pyautogui.click(614, 215)
    time.sleep(5)
    pyautogui.click(566, 223)
    time.sleep(5)
    pyautogui.click(504, 247)
    time.sleep(5)
    pyautogui.click(458, 273)
    time.sleep(5)
    pyautogui.click(420, 297)
    time.sleep(5)
    pyautogui.click(393, 334)
    time.sleep(5)
    pyautogui.click(385, 394)
    time.sleep(5)
    pyautogui.click(399, 447)
    time.sleep(5)
    pyautogui.click(424, 487)
    time.sleep(5)
    pyautogui.click(471, 510)
    time.sleep(5)
    pyautogui.click(506, 526)
    time.sleep(5)
    pyautogui.click(555, 535)
    time.sleep(5)
    pyautogui.click(599, 539)
    time.sleep(5)
    pyautogui.click(636, 538)
    time.sleep(5)
    pyautogui.click(680, 526)
    time.sleep(5)
    pyautogui.click(715, 512)
    time.sleep(5)
    pyautogui.click(757, 490)
    time.sleep(5)
    pyautogui.click(810, 452)
    time.sleep(5)
    pyautogui.click(845, 411)
    time.sleep(5)
    pyautogui.click(861, 372)
    time.sleep(5)
    pyautogui.click(855, 327)
    time.sleep(5)
    pyautogui.click(837, 290)
    time.sleep(5)
    pyautogui.click(811, 259)
    time.sleep(5)
    pyautogui.click(768, 234)
    time.sleep(5)
    pyautogui.click(723, 220)
    time.sleep(5)
    pyautogui.click(671, 214)
    time.sleep(5)
    pyautogui.click(614, 215)
    time.sleep(5)
    
def inputGranulation():
    
    X2btn = config.driver.find_element_by_xpath('/html/body/div[11]/button')
    X2btn.click()
    time.sleep(5)
    percenttb = config.driver.find_element_by_xpath('/html/body/div[12]/div/div/form/div/div[2]/div/div/table/tbody/tr/td[2]/table[2]/tbody/tr[2]/td[2]/table/tbody/tr/td/input[2]')
    percenttb.send_keys("95")
    time.sleep(5)
    pyautogui.click(1339, 124)
    time.sleep(5)
    
def SaveFunction():
    
    save1btn = config.driver.find_element_by_xpath('/html/body/div[12]/div/div/form/div/div[2]/div/div/table/tbody/tr/td[2]/div[3]/button[2]')
    save1btn.click()
    time.sleep(5)
    config.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(5)
    timein = config.driver.find_element_by_xpath('//*[@id="ti"]')
    timein.send_keys("23:00")
    time.sleep(5)
    timein = config.driver.find_element_by_xpath('//*[@id="to"]')
    timein.send_keys("23:30")
    time.sleep(5)
    save2btn = config.driver.find_element_by_xpath('//*[@id="tdTitleAction"]/td[2]/button')
    save2btn.click()
    time.sleep(5)
    woundtab = config.driver.find_element_by_xpath('//*[@id="profile-main-header"]/div/ul/li[8]')
    woundtab.click()
    time.sleep(5)
    woundHistory = config.driver.find_element_by_xpath('//*[@id="pinid1"]/span/span[1]')
    woundHistory.click()
    time.sleep(5)
    